import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import SignUp from './auth/signup'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Expiry - Track your groceries</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}

export default Home

export async function getServerSideProps(ctx: any) {
  return {
      props: {
          useAuth: true
      },
  }
}